version: "3.9"
services:
  auth_app:
    image: auth_app
    container_name: auth_app
    build: ./auth_app
    ports:
      - "9090:9090"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - auth_app
      - cocalc
    networks:
      - my-network

  cocalc:
    image: davidstritzl/cocalc
    container_name: cocalc
    restart: always
    ports:
      - "8888:443"
    networks:
      - my-network

networks:
  my-network:
